"""empty message

Revision ID: 1458cc3defa1
Revises: 334afdcdc815
Create Date: 2022-10-22 11:41:17.546023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1458cc3defa1'
down_revision = '334afdcdc815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.String(length=255), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('like_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
