"""empty message

Revision ID: 6764b20cd5d5
Revises: 1458cc3defa1
Create Date: 2022-10-25 15:12:38.117521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6764b20cd5d5'
down_revision = '1458cc3defa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscribe_time', sa.DateTime(), nullable=True),
    sa.Column('u_id', sa.String(length=200), nullable=True),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['t_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('img_urls', sa.String(length=200), nullable=True))
    op.add_column('post', sa.Column('video_urls', sa.String(length=200), nullable=True))
    op.add_column('post', sa.Column('author_id', sa.String(length=200), nullable=False))
    op.alter_column('post', 'topic_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'post', 'topic', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    op.drop_column('post', 'img_url')
    op.drop_column('post', 'author')
    op.drop_column('post', 'video_url')
    op.add_column('response', sa.Column('author_id', sa.String(length=200), nullable=False))
    op.alter_column('response', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'response', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'response', 'user', ['author_id'], ['id'])
    op.drop_column('response', 'author')
    op.add_column('topic', sa.Column('img_urls', sa.String(length=200), nullable=True))
    op.add_column('topic', sa.Column('video_urls', sa.String(length=200), nullable=True))
    op.add_column('topic', sa.Column('author_id', sa.String(length=200), nullable=False))
    op.create_foreign_key(None, 'topic', 'user', ['author_id'], ['id'])
    op.drop_column('topic', 'author')
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('topic', sa.Column('author', mysql.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'author_id')
    op.drop_column('topic', 'video_urls')
    op.drop_column('topic', 'img_urls')
    op.add_column('response', sa.Column('author', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.drop_constraint(None, 'response', type_='foreignkey')
    op.alter_column('response', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('response', 'author_id')
    op.add_column('post', sa.Column('video_url', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('post', sa.Column('author', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('post', sa.Column('img_url', mysql.VARCHAR(length=200), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'topic_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('post', 'author_id')
    op.drop_column('post', 'video_urls')
    op.drop_column('post', 'img_urls')
    op.drop_table('subscription')
    # ### end Alembic commands ###
