"""empty message

Revision ID: b38b0d85f416
Revises: 6764b20cd5d5
Create Date: 2022-10-27 10:13:49.955398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b38b0d85f416'
down_revision = '6764b20cd5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('type_id', mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
