"""empty message

Revision ID: b9d05d9a35ef
Revises: b38b0d85f416
Create Date: 2022-10-27 10:31:04.379001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9d05d9a35ef'
down_revision = 'b38b0d85f416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('topic', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('topic', 'create_time')
    # ### end Alembic commands ###
